default: &default
  adapter: postgresql
  encoding: unicode
  user: vinetac
  password: 314
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: backend_development


